=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/schemas/emojis-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "object",
  "properties": {
    "+1": {
      "required": false,
      "type": "string"
    },
    "-1": {
      "required": false,
      "type": "string"
    },
    "100": {
      "required": false,
      "type": "string"
    },
    "1234": {
      "required": false,
      "type": "string"
    },
    "8ball": {
      "required": false,
      "type": "string"
    },
    "a": {
      "required": false,
      "type": "string"
    },
    "ab": {
      "required": false,
      "type": "string"
    }
  }
}

=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/examples/emojis-example.json
{
  "+1": "https://github.global.ssl.fastly.net/images/icons/emoji/+1.png?v5",
  "-1": "https://github.global.ssl.fastly.net/images/icons/emoji/-1.png?v5",
  "100": "https://github.global.ssl.fastly.net/images/icons/emoji/100.png?v5",
  "1234": "https://github.global.ssl.fastly.net/images/icons/emoji/1234.png?v5",
  "8ball": "https://github.global.ssl.fastly.net/images/icons/emoji/8ball.png?v5",
  "a": "https://github.global.ssl.fastly.net/images/icons/emoji/a.png?v5",
  "ab": "https://github.global.ssl.fastly.net/images/icons/emoji/ab.png?v5"
}
