=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/schemas/feeds-schema.json
{
    "$schema": "http://json-schema.org/draft-03/schema",
    "type": "object",
    "properties": {
    	"timeline_url": {
    		"type": "string"
    	},
    	"user_url": {
    		"type": "string"
    	},
    	"current_user_public": {
    		"type": "string"
    	},
    	"current_user_url": {
    		"type": "string"
    	},
    	"current_user_actor_url": {
    		"type": "string"
    	},
    	"current_user_organization_url": {
    		"type": "string"
    	},
    	"_links": {
    		"properties": {
    			"timeline": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			},
    			"user": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			},
    			"current_user_public": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			},
    			"current_user": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			},
    			"current_user_actor": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			},
    			"current_user_organization": {
    				"properties": {
    					"href": {
    						"type": "string"
    					},
    					"type": {
    						"type": "string"
    					}
    				},
    				"type": "object"
    			}
    		}
    	}
    }
}

=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/examples/feeds-example.json
{
  "timeline_url": "https://github.com/timeline",
  "user_url": "https://github.com/{user}",
  "current_user_public": "https://github.com/defunkt",
  "current_user_url": "https://github.com/defunkt.private?token=abc123",
  "current_user_actor_url": "https://github.com/defunkt.private.actor?token=abc123",
  "current_user_organization_url": "https://github.com/organizations/{org}/defunkt.private.atom?token=abc123",
  "_links": {
    "timeline": {
      "href": "https://github.com/timeline",
      "type": "application/atom+xml"
    },
    "user": {
      "href": "https://github.com/{user}",
      "type": "application/atom+xml"
    },
    "current_user_public": {
      "href": "https://github.com/defunkt",
      "type": "application/atom+xml"
    },
    "current_user": {
      "href": "https://github.com/defunkt.private?token=abc123",
      "type": "application/atom+xml"
    },
    "current_user_actor": {
      "href": "https://github.com/defunkt.private.actor?token=abc123",
      "type": "application/atom+xml"
    },
    "current_user_organization": {
      "href": "https://github.com/organizations/{org}/defunkt.private.atom?token=abc123",
      "type": "application/atom+xml"
    }
  }
}
