=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/schemas/repoCommit-schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "properties": {
    "sha": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "author": {
      "type": "object",
      "properties": {
        "date": {
          "description": "ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "committer": {
      "type": "object",
      "properties": {
        "date": {
          "description": "ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "message": {
      "type": "string"
    },
    "tree": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "sha": {
          "type": "string"
        }
      }
    },
    "parents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          },
          "sha": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== mulesoft-labs/raml-object-standard/test/fixtures/github_v3/examples/repoCommits-example.json
{
  "sha": "7638417db6d59f3c431d3e1f261cc637155684cd",
  "url": "https://api.github.com/repos/octocat/Hello-World/git/commits/7638417db6d59f3c431d3e1f261cc637155684cd",
  "author": {
    "date": "2008-07-09T16:13:30+12:00",
    "name": "Scott Chacon",
    "email": "schacon@gmail.com"
  },
  "committer": {
    "date": "2008-07-09T16:13:30+12:00",
    "name": "Scott Chacon",
    "email": "schacon@gmail.com"
  },
  "message": "my commit message",
  "tree": {
    "url": "https://api.github.com/repos/octocat/Hello-World/git/trees/827efc6d56897b048c772eb4087f854f46256132",
    "sha": "827efc6d56897b048c772eb4087f854f46256132"
  },
  "parents": [
    {
      "url": "https://api.github.com/repos/octocat/Hello-World/git/commits/7d1b31e74ee336d15cbd21741bc88a537ed063a0",
      "sha": "7d1b31e74ee336d15cbd21741bc88a537ed063a0"
    }
  ]
}
